# Generated by Django 4.2.4 on 2023-09-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ListaDeTareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listatareas',
            old_name='idUsario',
            new_name='idUsuario',
        ),
    ]
