# Generated by Django 4.2.5 on 2023-09-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ListaDeTareas', '0004_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
