# Generated by Django 4.2.5 on 2023-09-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ListaDeTareas', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
